template: |
  *All updates are also available through [FilterBlade](https://www.filterblade.xyz) and on the [PoE filter ladder](https://www.pathofexile.com/item-filter/ladder/follower). Major thanks to all patreon supporters to help us fund the continuous development. [Patreon](https://www.patreon.com/Neversink) supporters also receive a Patreon-exclusive [Filter-Auto-Updater](https://youtu.be/i8RJx0s0zsA).*
  
  - Overhauled the divination card tiering algorithm. The new setup is not perfect (divination card economy data is VERY unreliable on the lower end), but it should be a significant upgrade
  - Integrated all new uniques, divination cards, fragments etc into the tiering
  - Further improved the 'Expensive Basetype' rule to better detect currently valuable bases. This is a work in progress.
  - Further improved tiering of Talismans
  - Added new unique tiering rules
  - Added economy based ducat tiering
  - Added economy based enshrouding crystal tiering
  - Integrated the new ducat
  - Added the new unique shield
  
  ------

  Developed by NeverSink

  [![Follow me on Twitter](https://img.shields.io/badge/twitter-grey.svg?style=for-the-badge&logo=twitter)](https://twitter.com/NeverSinkDev) [![FilterBlade Discord](https://img.shields.io/badge/discord-grey.svg?style=for-the-badge&logo=discord)](https://discord.gg/mye6xhF) [![Watch FB Dev on Twitch](https://img.shields.io/badge/twitch-grey.svg?style=for-the-badge&logo=twitch)](https://twitch.tv/neversink) [![Support development on Patreon](https://img.shields.io/badge/patreon-grey.svg?style=for-the-badge&logo=patreon)](https://www.patreon.com/Neversink)
